name: Update Maintainers

on:
  pull_request:
    types: [closed]

jobs:
  update-maintainers:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Sync maintainers
        run: java -jar SyncMaintainers.jar
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
